# -*- coding: utf-8 -*-
"""CSE303Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-Iy7P2pOxhCTPMCy9PgRXnhFyJCmb-P

**Basic Input Output**
"""

print("Hello World")

name = "Shajib"
age = 23
print("My name is %s and I'm %d years old"%(name,age))

name = input("Enter your name: ")
age = int(input("Enter your age: "))
print(f"{name} is {age} years old")

"""**Operators and Conditinal Statement**"""

n = 5
inp = int(input("Enter a number : "))

if inp>5:
  print("%d is smaller than %d"%(n,inp))
elif inp<5:
  print("%d is bigger than %d"%(n,inp))
elif inp == n:
  print("Numbers are equal")

if(n!=inp):
  print("Numbers are not equal")

marks = 60
n = int(input("Enter your exam marks: "))
if n<=marks-1:
  print("Your result is fail.")
elif n>=marks:
  print("Your result is pass.")

if(n>=90):
  print("You got A+")

marks = int(input("Enter your marks : "))

if marks>=97:
  print("Result : A+")
elif marks>=90:
  print("Result : A")
elif marks<90 and marks>=80:
  print("Result : B")
elif marks<80 and marks>=70:
  print("Result : C")
elif marks<70 and marks>=60:
  print("Result : C")
else:
  print("Result : Fail")

#Checking Leap Year
year = int(input("Enter any year : "))

if year%4 == 0 and year%100 !=0 or year%400==0:
  print("%d is Leap Year"%(year))
else:
  print("%d is not leap year"%(year))

"""**Loop**"""

n = 5
for i in range(n):
  for j in range(i):
    print("#",end="")
  print("\n")

list = [1,2,3,4]
for i in list:
  print(i,end=" ")

"""**List**, **Touple**, **Set**, **Dictonary**"""

list = [1,2,"Shajib", "EWU", 1.50, 5/2, 5//2] #work with multipe datatype
print("Print List : ",end="")
for i in list:
  print(i, end=" ")
print("\nPrint Touple : ", end="")
touple = (2.5, "Shajib")
print(touple)

print("Print Set : ",end="")
set = {1,2,1,1,2,3,4,4,4,5,5,5,5} #remove duplicate
print(set)

dic = {1:'a', 2:'b', 3:'c'}#key value
print(dic)
print(dic[2])

"""**Use of List Methods**"""

list = [10, 10, 10, 20, 30, "Shajib", 'a', 'b', 'c']
print("My List : ",list)

list.append("Hasib")
print("After append() : ",list)

CopyList = list.copy()
print("List after copy : ",CopyList)

CopyList.clear()
print("Clear Copied List = ",CopyList)

print("Count of 10 is : ",list.count(10))
print("Index of 20 is : ",list.index(20))

list.insert(5,"Rakib")
print("Insert Rakib in index 5 : ",list)

list.pop(0)
list.pop(1)
print("Remove index 0,1 from the list : ",list)

list.remove(30)
print("Remove 30 from the list : ",list)

list.reverse()
print("My List after reverse : ",list)

newList = [4, 5, 2, 1, 3]
newList.sort()
print("My List after sort : ",newList)

list.extend(newList)
print("Concate 2 list using extend : ",list)

"""**Use of Dictonary Method**"""

dic = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e'}
print("My Dictonary : ",dic)

print("Element in key 3 : ",dic[3])

dic2 = dic.copy()
print("My Dictonary2 after copye : ",dic2)

dic2.clear()
print("My Dictonary2 after clear : ",dic2)

x = ('k1', 'k2', 'k3')
y = 5
thisdict = dict.fromkeys(x, y)
print("My Dictonary : ",thisdict)

print("Value in key(5) : ",dic.get(5))

print("All item/value : ",dic.items())
print("All key list : ",dic.keys())

dic.pop(5)
print("My Dictonary after remove key(5) : ",dic)

dic.popitem()
print("My Dictonary after remove Last item : ",dic)

dic.setdefault(3,'c')#already in the dict
dic.setdefault(4,'d')#not in current dict
print("My Dictonary : ",dic)#set the new key(4) with value

print("All values : ",dic.values())

dic.update({1:'x'})
print("My Dictonary after update key(1) : ",dic)

"""**Functions**"""

def sum(a,b):
  return a+b

#printing fibonacci series
n = int(input("Enter value : "))

if n==1:
  print(0)
elif n==2:
  print(0,end=" ")
  print(1)
else:
  l = 0
  r = 1
  print(l,end=" ")
  print(r,end=" ")
  while n>2:
    temp = sum(l,r)
    print(temp,end=" ")
    l = r
    r = temp
    n = n - 1

"""**Indexing and Slicing**"""

list = [1, 2, 3, 'a', 'b', 'c']
print("My List : ",list)
print("Index 0 : ",list[0])
print("Last index value using len : ",list[len(list)-1])
print("Last index value using negaive index : ",list[-1])

print("My List : ",list[:])
print("My List : ",list[:4])
print("My List : ",list[2:5])
print("My List : ",list[0:len(list):2])#increment 2
print("My List : ",list[:-2])
print("My List : ",list[2:-2])